=== jintachi/GWJ85/mechanics/inventory_system/items.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "title": "Item Compendium",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": { "type": "integer" },
            "name": { "type": "string" },
            "description": {"type": "string"},
            "value": { "type": "integer" },
            "texture_pos": {
                "type": "object",
                "x": { "type": "integer" },
                "y": { "type": "integer" },
                "required": [ "x", "y" ]
            },
            "purchaseable": { "type" : "boolean" },
            "cost": { "type": "integer" },
            "producer_id": { "type": "integer" }
        },
        "required": [ "id", "name", "description", "value", "texture_pos" ],
        "additionalProperties": false
    }
}

=== jintachi/GWJ85/mechanics/inventory_system/items.json
[
    {
        "id": 0,
        "name": "Pumpkin Seed",
        "description": "A pumpkin seed",
        "value": 1,
        "texture_pos": {
            "x": 0,
            "y": 0
        },
        "purchaseable": true
    },
    {
        "id": 1,
        "name": "Carrot Seed",
        "description": "Grows carrots",
        "value": 1,
        "texture_pos": {
            "x": 0,
            "y": 0
        },
        "purchaseable": true
    },
    {
        "id": 3,
        "name": "Toasted Pumpkin Seed",
        "description": "If you like that sort of thing.",
        "value": 3,
        "texture_pos": {
            "x": 0,
            "y": 0
        },
        "purchaseable": false
    }
]
